export const styles = {
  heroSection: (isSmall: boolean) => ({
    position: "relative",
    backgroundImage: "url(../src/assets/headerBackground.png)",
    backgroundRepeat: "no-repeat",
    WebkitBackgroundSize: "cover",
    backgroundSize: "cover",
    WebkitBackgroundPosition: "center",
    backgroundPosition: "center",
    backgroundColor: "#f9faff",
    backgroundBlendMode: "multiply",
    paddingTop: isSmall ? 0 : "80px",
    paddingLeft: isSmall ? "12px" : "120px",
    width: isSmall ? "100%" : "55%",
    flex: "1 1 0",
  }),
  heroSectionTypography: {
    position: "absolute",
    width: "15.5%",
    height: "168px",
    backgroundColor: "#FFBB00",
    WebkitClipPath: [
      "polygon(50% 0, 100% 25%, 100% 75%, 50% 100%, 0 75%, 0 25%)",
      "polygon(50% 0, 100% 25%, 100% 75%, 50% 100%, 0 75%, 0 25%)",
    ],
    clipPath: "polygon(50% 0, 100% 25%, 100% 75%, 50% 100%, 0 75%, 0 25%)",
    zIndex: 0,
    opacity: 0.09,
    borderRadius: "30px",
    top: "-81px",
    left: "29.5%",
  },
  heroRightPolygon: (isSmall: boolean) => ({
    position: "absolute",
    width: isSmall ? "354px" : "463px",
    height: "723px",
    backgroundColor: "#FFBB00",
    WebkitClipPath:
      "polygon(50% 0, 100% 25%, 100% 75%, 50% 100%, 0 75%, 0 25%)",
    clipPath: "polygon(50% 0, 100% 25%, 100% 75%, 50% 100%, 0 75%, 0 25%)",
    zIndex: 0,
    opacity: 0.09,
    borderRadius: "30px",
    top: "-319px",
    right: 0,
  }),
  container: (isSmall: boolean) => ({
    display: "flex",
    pr: { md: "100px", sm: "10px", xs: "20px" },
    pl: { md: "120px", sm: "20px", xs: "20px" },
    flexDirection: "column",
    gap: isSmall ? "50px" : "120px",
    mt: 10,
  }),
  features: (isLastCol: boolean, isLastRow: boolean) => ({
    display: "flex",
    minHeight: "94px",
    gap: "17px",
    flexDirection: "row",
    padding: "26px 24px",
    alignItems: "center",
    width: {
      xs: "50%",
      md: "25%",
    },
    boxSizing: "border-box",
    borderRight: isLastCol ? "none" : "1px solid #E5E5E7",
    borderBottom: isLastRow ? "none" : "1px solid #E5E5E7",
    "& .oneLiner": {
      opacity: 0,
      maxHeight: 0,
      overflow: "hidden",
      transition: "all 0.3s ease-in-out",
    },
    transition: "all 0.3s ease-in-out",
    "&:hover": {
      borderRadius: "6px",
      boxShadow: "0px 1.08px 8.63px 0px rgba(0, 0, 0, 0.06)",
      fontWeight: 600,
      "& .oneLiner": {
        opacity: 1,
        maxHeight: "100px",
      },
    },
  }),
  featureCard: {
    width: "142px",
    height: "44px",
    p: "12px",
    boxShadow: "0px 1.08px 8.63px 0px rgba(0, 0, 0, 0.06);",
    borderRadius: "12px",
  },
  footContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    mt: "125.84px",
  },
  appPreview: {
    position: "absolute",
    left: 31.8,
    top: "41.3%",
    transform: "translateY(-50%)",
    width: "399.84px",
    height: "469.9px",
    zIndex: 2,
  },
  appPreviewCard: {
    height: "195px",
    padding: "70px 40px",
    borderRadius: "12px",
    mt: "66px",
    boxShadow: "0px 1.08px 8.63px 0px rgba(0, 0, 0, 0.06);",
    width: "100%",
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "row-reverse",
  },
};
